helmDefaults:
  diffArgs:
    - --dry-run=server

releases:
  - name: kube-prometheus-stack
    chart: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
    namespace: monitoring
    set:
      - { name: defaultRules.create, value: false }
      - { name: prometheus.prometheusSpec.ruleSelectorNilUsesHelmValues, value: false }
      - { name: grafana.defaultDashboardsEnabled, value: false }
      - { name: grafana.sidecar.dashboards.folderAnnotation, value: grafana_folder }
      - { name: grafana.sidecar.dashboards.provider.foldersFromFilesStructure, value: true }
      - { name: grafana.adminUser, value: admin }
      - { name: grafana.adminPassword, value: supersecret }

  - name: kubernetes-mixin
    chart: ../chart
    namespace: monitoring
    needs: [monitoring/kube-prometheus-stack]
    set:
      - { name: mixinName, value: kubernetes }
      - { name: dashboard.folderName, value: Kubernetes }

  - name: node-exporter-mixin
    chart: ../chart
    namespace: monitoring
    needs: [monitoring/kube-prometheus-stack]
    set:
      - { name: mixinName, value: node-exporter }
      - { name: dashboard.folderName, value: "Node Exporter" }
